### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by zhenfang0215** [vufa/gorequest#1]
hi, I had a panic while using gorequest, And I can't reproduce the problem. 
```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 152485 [running]:
runtime.throw({0x2e2f288, 0x2a08520})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc02ce5d6a8 sp=0xc02ce5d678 pc=0x4358b1
runtime.mapassign_faststr(0x2a65ce0, 0xc02ce37aa0, {0x2e132f5, 0xd})
        /usr/local/go/src/runtime/map_faststr.go:294 +0x38b fp=0xc02ce5d710 sp=0xc02ce5d6a8 pc=0x41304b
net/textproto.MIMEHeader.Set(...)
        /usr/local/go/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /usr/local/go/src/net/http/header.go:38
github.com/parnurzeal/gorequest.(*SuperAgent).Set(...)
        /go/pkg/mod/github.com/parnurzeal/gorequest@v0.2.16/gorequest.go:371
```

**Comment by zhenfang0215** [comment]
> hi, I had a panic while using gorequest, And I can't reproduce the problem.
> 
> ```
> fatal error: concurrent map writes
> fatal error: concurrent map writes
> 
> goroutine 152485 [running]:
> runtime.throw({0x2e2f288, 0x2a08520})
>         /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc02ce5d6a8 sp=0xc02ce5d678 pc=0x4358b1
> runtime.mapassign_faststr(0x2a65ce0, 0xc02ce37aa0, {0x2e132f5, 0xd})
>         /usr/local/go/src/runtime/map_faststr.go:294 +0x38b fp=0xc02ce5d710 sp=0xc02ce5d6a8 pc=0x41304b
> net/textproto.MIMEHeader.Set(...)
>         /usr/local/go/src/net/textproto/header.go:22
> net/http.Header.Set(...)
>         /usr/local/go/src/net/http/header.go:38
> github.com/parnurzeal/gorequest.(*SuperAgent).Set(...)
>         /go/pkg/mod/github.com/parnurzeal/gorequest@v0.2.16/gorequest.go:371
> ```

version：[v0.2.16](https://github.com/vufa/gorequest/releases/tag/v0.2.16)
